# Generated by Django 3.0.6 on 2020-05-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0004_auto_20200512_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='users',
        ),
        migrations.DeleteModel(
            name='DisLike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
