# Generated by Django 3.0.6 on 2020-05-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0006_post_user_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_like',
        ),
    ]
