# Generated by Django 3.0 on 2020-05-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0007_remove_post_user_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
