# Generated by Django 3.0 on 2020-05-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0008_auto_20200513_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
